set_property IOSTANDARD LVCMOS33 [get_ports {Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Blue[0]}]
set_property PACKAGE_PIN N18 [get_ports {Blue[0]}]
set_property PACKAGE_PIN L18 [get_ports {Blue[1]}]
set_property PACKAGE_PIN K18 [get_ports {Blue[2]}]
set_property PACKAGE_PIN J18 [get_ports {Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Green[0]}]
set_property PACKAGE_PIN J17 [get_ports {Green[0]}]
set_property PACKAGE_PIN H17 [get_ports {Green[1]}]
set_property PACKAGE_PIN G17 [get_ports {Green[2]}]
set_property PACKAGE_PIN D17 [get_ports {Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Red[0]}]
set_property PACKAGE_PIN G19 [get_ports {Red[0]}]
set_property PACKAGE_PIN H19 [get_ports {Red[1]}]
set_property PACKAGE_PIN J19 [get_ports {Red[2]}]
set_property PACKAGE_PIN N19 [get_ports {Red[3]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN P19 [get_ports Hsynq]
set_property PACKAGE_PIN R19 [get_ports Vsynq]
set_property PACKAGE_PIN B16 [get_ports jumpButton]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Hsynq]
set_property IOSTANDARD LVCMOS33 [get_ports Vsynq]
set_property IOSTANDARD LVCMOS33 [get_ports jumpButton]

set_property PACKAGE_PIN G2 [get_ports duckButton]
set_property IOSTANDARD LVCMOS33 [get_ports duckButton]


set_property PACKAGE_PIN E19 [get_ports collided]
set_property IOSTANDARD LVCMOS33 [get_ports collided]

set_property PACKAGE_PIN L1 [get_ports dead]
set_property PACKAGE_PIN P1 [get_ports run]
set_property IOSTANDARD LVCMOS33 [get_ports dead]
set_property IOSTANDARD LVCMOS33 [get_ports run]

set_property PACKAGE_PIN U18 [get_ports resetButton]
set_property IOSTANDARD LVCMOS33 [get_ports resetButton]

set_property PACKAGE_PIN V17 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]


